"""
Django settings for aiecommerce project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decimal import Decimal
from pathlib import Path

import environ  # Import environ

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
)

BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))

# SECURITY WARNING: keep the secret key used in production secret!
# Provide a dev default so the server can start locally without a .env.
SECRET_KEY = env("SECRET_KEY", default="change-me-in-env")

DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Security settings for HTTPS development
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "aiecommerce",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aiecommerce.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aiecommerce.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(
        default=f"sqlite:///{(BASE_DIR / 'db.sqlite3')}",
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Guayaquil"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Celery Configuration
# Default to local Redis (matches your docker-compose redis service).
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
CELERY_TIMEZONE = "America/Guayaquil"  # Ensures 8am means 8am in your local time
CELERY_ENABLE_UTC = True

# Tecnomega Configuration
PRICE_LIST_BASE_URL = env("PRICE_LIST_BASE_URL", default="")
TECNOMEGA_STOCK_LIST_BASE_URL = env("TECNOMEGA_STOCK_LIST_BASE_URL", default="")
TECNOMEGA_SCRAPE_CATEGORIES = env("TECNOMEGA_SCRAPE_CATEGORIES", default="")

# --- Mercado Libre Configuration ---
MERCADOLIBRE_FRESHNESS_THRESHOLD_HOURS = env.int("MERCADOLIBRE_FRESHNESS_THRESHOLD_HOURS", default=24)
MERCADOLIBRE_PUBLICATION_RULES = env.json(
    "MERCADOLIBRE_PUBLICATION_RULES",
    default={
        "NOTEBOOK": {"price_threshold": 1000.00},
        "MONITOR": {"price_threshold": 0.00},
        "COMPUTER": {"price_threshold": 500.00},
    },
)
MERCADOLIBRE_BASE_URL = env("MERCADOLIBRE_BASE_URL", default="https://api.mercadolibre.com")
MERCADOLIBRE_AUTH_URL = env("MERCADOLIBRE_AUTH_URL", default="https://auth.mercadolibre.com.ec")
MERCADOLIBRE_CLIENT_ID = env("MERCADOLIBRE_CLIENT_ID", default="")
MERCADOLIBRE_CLIENT_SECRET = env("MERCADOLIBRE_CLIENT_SECRET", default="")
MERCADOLIBRE_REDIRECT_URI = env("MERCADOLIBRE_REDIRECT_URI", default="https://127.0.0.1:8000/mercadolibre/callback/")

# --- Google API Configuration ---
GOOGLE_API_KEY = env("GOOGLE_API_KEY", default="")
GOOGLE_SEARCH_ENGINE_ID = env("GOOGLE_SEARCH_ENGINE_ID", default="")
IMAGE_SEARCH_COUNT = env.int("IMAGE_SEARCH_COUNT", default=12)

# --- Mercado Price Engine ---
MERCADOLIBRE_IVA_RATE = env("MERCADOLIBRE_IVA_RATE", cast=Decimal, default=Decimal("0.15"))
MERCADOLIBRE_COMMISSION_RATE = env("MERCADOLIBRE_COMMISSION_RATE", cast=Decimal, default=Decimal("0.10"))
MERCADOLIBRE_SHIPPING_FEE = env("MERCADOLIBRE_SHIPPING_FEE", cast=Decimal, default=Decimal("5.00"))
MERCADOLIBRE_TARGET_MARGIN = env("MERCADOLIBRE_TARGET_MARGIN", cast=Decimal, default=Decimal("0.15"))
MERCADOLIBRE_OPERATIONAL_COST = env("MERCADOLIBRE_OPERATIONAL_COST", cast=Decimal, default=Decimal("5.00"))

# --- AWS S3 Configuration ---
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
