# Generated by Django 6.0 on 2025-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("price_distributor", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("availability_status", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductRawPDF",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_description", models.TextField(blank=True, null=True)),
                ("distributor_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("category_header", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductRawWeb",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_description", models.TextField(blank=True, null=True)),
                ("scraped_availability", models.TextField(blank=True, null=True)),
                ("product_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("raw_html", models.TextField(blank=True, null=True)),
                ("search_term", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
