# Generated by Django 6.0 on 2025-12-22 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productrawweb",
            old_name="product_url",
            new_name="image_url",
        ),
        migrations.RemoveField(
            model_name="productrawweb",
            name="scraped_availability",
        ),
        migrations.RemoveField(
            model_name="productrawweb",
            name="sku",
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="distributor_code",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="scrape_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="stock_colon",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="stock_gye_norte",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="stock_gye_sur",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="stock_principal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productrawweb",
            name="stock_sur",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="productrawweb",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
