# Generated by Django 6.0 on 2025-12-23 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0002_rename_product_url_productrawweb_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmaster",
            old_name="brand",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="productmaster",
            old_name="price_distributor",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="availability_status",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="sku",
        ),
        migrations.AddField(
            model_name="productmaster",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="stock_colon",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="stock_gye_norte",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="stock_gye_sur",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="stock_principal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="stock_sur",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
