# Generated by Django 6.0 on 2025-12-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0003_rename_brand_productmaster_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="specs",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
