# Generated by Django 6.0 on 2025-12-27 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0004_productmaster_specs"),
    ]

    operations = [
        migrations.CreateModel(
            name="MercadoLibreListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ml_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The unique identifier for the listing on Mercado Libre.",
                        max_length=24,
                        null=True,
                        unique=True,
                        verbose_name="Mercado Libre ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACTIVE", "Active"), ("PAUSED", "Paused"), ("ERROR", "Error")],
                        db_index=True,
                        default="PENDING",
                        help_text="The current status of the listing.",
                        max_length=10,
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(blank=True, help_text="When the listing was last synced with Mercado Libre.", null=True, verbose_name="Last Synced"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, help_text="Details of the last synchronization error, if any.", null=True, verbose_name="Sync Error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_master",
                    models.OneToOneField(
                        help_text="The master product associated with this listing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mercadolibre_listing",
                        to="aiecommerce.productmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mercado Libre Listing",
                "verbose_name_plural": "Mercado Libre Listings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
