# Generated by Django 6.0 on 2025-12-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0005_mercadolibrelisting"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mercadolibrelisting",
            index=models.Index(fields=["status", "last_synced"], name="aiecommerce_status_d4f3a4_idx"),
        ),
    ]
