# Generated by Django 6.0 on 2025-12-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0006_mercadolibrelisting_aiecommerce_status_d4f3a4_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="MercadoLibreToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
