# Generated by Django 6.0 on 2025-12-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0007_mercadolibretoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercadolibretoken",
            name="is_test_user",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
