# Generated by Django 6.0 on 2025-12-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0008_add_is_test_user_to_mercadolibretoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=2000)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="aiecommerce.productmaster"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
