# Generated by Django 6.0 on 2025-12-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0009_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="is_for_mercadolibre",
            field=models.BooleanField(default=False),
        ),
    ]
