# Generated by Django 6.0 on 2026-01-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0010_productmaster_is_for_mercadolibre"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="seo_description",
            field=models.TextField(
                blank=True, help_text="AI-generated plain text description including storytelling and specs.", null=True
            ),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="seo_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="AI-generated title optimized for marketplaces (Max 60 chars).",
                max_length=60,
                null=True,
            ),
        ),
    ]
