# Generated by Django 6.0 on 2026-01-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0011_productmaster_seo_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="sku",
            field=models.CharField(blank=True, db_index=True, help_text="Manufacturer Part Number (MPN or SKU).", max_length=255, null=True),
        ),
    ]
