# Generated by Django 6.0 on 2026-01-06 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0012_productmaster_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetailScrape",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("attributes", models.JSONField(default=dict)),
                ("image_urls", models.JSONField(default=list)),
                ("raw_html", models.TextField(blank=True, null=True)),
                ("scrape_session_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(help_text="The master product this scrape belongs to.", on_delete=django.db.models.deletion.CASCADE, related_name="detail_scrapes", to="aiecommerce.productmaster")),
            ],
        ),
    ]
