# Generated by Django 6.0 on 2026-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0013_productdetailscrape"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="gtin",
            field=models.CharField(blank=True, db_index=True, help_text="Verified EAN/GTIN/UPC code.", max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="gtin_source",
            field=models.CharField(blank=True, help_text="Strategy used: google_search, ean_search_api, etc.", max_length=50, null=True),
        ),
    ]
