# Generated by Django 6.0 on 2026-01-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0014_productmaster_gtin_productmaster_gtin_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="model_name",
            field=models.CharField(blank=True, db_index=True, help_text="The specific model identifier (e.g., ProBook 440 G10).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, help_text="Standardized name: [Brand] [Line] [Model] [Specs]", max_length=255, null=True),
        ),
    ]
