# Generated by Django 6.0 on 2026-01-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0015_productmaster_model_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercadolibrelisting",
            name="category_id",
            field=models.CharField(blank=True, help_text="The category ID for the listing on Mercado Libre.", max_length=30, null=True, verbose_name="Mercado Libre Category ID"),
        ),
    ]
