# Generated by Django 6.0 on 2026-01-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0016_mercadolibrelisting_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercadolibrelisting",
            name="final_price",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The final price of the listing on Mercado Libre.", max_digits=10, null=True, verbose_name="Final Price"),
        ),
        migrations.AddField(
            model_name="mercadolibrelisting",
            name="net_price",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The net price of the listing before Mercado Libre fees.", max_digits=10, null=True, verbose_name="Net Price"),
        ),
        migrations.AddField(
            model_name="mercadolibrelisting",
            name="profit",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The estimated profit from the listing.", max_digits=10, null=True, verbose_name="Profit"),
        ),
    ]
