# Generated by Django 6.0 on 2026-01-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0017_mercadolibrelisting_final_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercadolibrelisting",
            name="available_quantity",
            field=models.IntegerField(blank=True, help_text="The available stock quantity on Mercado Libre.", null=True, verbose_name="Available Quantity"),
        ),
    ]
