# Generated by Django 6.0 on 2026-01-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiecommerce", "0018_mercadolibrelisting_available_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercadolibrelisting",
            name="attributes",
            field=models.JSONField(blank=True, help_text="JSON field to store Mercado Libre attributes.", null=True, verbose_name="Mercado Libre Attributes"),
        ),
    ]
