# Generated by Django 6.0 on 2026-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiecommerce', '0019_mercadolibrelisting_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='last_bundled_date',
            field=models.DateTimeField(blank=True, help_text='Tracks when a component was last used in a published bundle.', null=True),
        ),
    ]
